version: "2"
services:
  mysql:
    container_name: book-shop-clone
    image: mysql:8.0
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    ports:
      - 13307:3306
    volumes:
      - shop-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shopclone_root
      MYSQL_DATABASE: bookshopclone
      MYSQL_USER: shopclone_user
      MYSQL_PASSWORD: shopclone_pass

volumes:
  shop-mysql: